---
- name: Full NiFi Deployment
  hosts: nifi
  become: yes

  vars:
    nifi_properties_file: /home/ubuntu/nifi-1.26.0-bin/nifi-1.26.0/conf/nifi.properties # Adjust path
    nifi_home: /home/ubuntu/nifi-1.26.0-bin/nifi-1.26.0/
    nifi_start_file: /home/ubuntu/nifi-1.26.0-bin/nifi-1.26.0/bin/nifi.sh
    nifi_file_name: nifi-1.26.0-bin
    java_home: /usr/lib/jvm/java-17-openjdk-amd64

  tasks:
    - name: Ensure JAVA_HOME is in /etc/environment
      lineinfile:
        path: /etc/environment
        regexp: '^JAVA_HOME='
        line: 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'
        create: yes

    - name: Source /etc/environment and start NiFi with nohup (as ubuntu)
      become: yes
      become_user: ubuntu
      shell: |
        source /etc/environment
        nohup /home/ubuntu/nifi-1.26.0/bin/nifi.sh start > /tmp/nifi-ansible.log 2>&1 &
      args:
        executable: /bin/bash